# Generated by Django 4.2 on 2024-04-13 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Nombre de la universidad', max_length=255)),
                ('search', models.CharField(help_text='Búsqueda asociada para la universidad', max_length=255)),
                ('codigo', models.CharField(blank=True, default='', help_text='Razón social de la universidad', max_length=255)),
                ('rfc', models.CharField(help_text='Registro Federal de Contribuyentes de la universidad', max_length=13)),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('universidad', models.ForeignKey(help_text='Corporativo al que pertenece la empresa', on_delete=django.db.models.deletion.CASCADE, related_name='universidad_link', to='universidad.universidad')),
                ('updated_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plantel',
                'ordering': ['-id'],
            },
        ),
    ]
